version: '3.8'
services:
  tax-bot:
    build: .
    container_name: ogn-tracker
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./logs:/root/logs
    restart: always
